title: The Donut Factory
description: Writing projects by Kargas Dolunt
theme: just-the-docs

url: https://kargas-dolunt.github.io/donut-factory


aux_links:
  Fediverse: https://dice.camp/@cwdolunt
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
